apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krateo-frontend.fullname" . }}-config-vars
  labels:
    {{- include "krateo-frontend.labels" . | nindent 4 }}
data:
  config.json: |
    {"api":{
{{- $local := dict "first" true -}}
{{- range $k, $v := .Values.config -}}
{{- if not $local.first -}},{{- end -}}
{{- if kindIs "string" $v }}
  {{ quote $k | indent 6 }}: {{ quote $v }}
{{- else }}
  {{ quote $k | indent 6 }}: {{ $v }}
{{- end }}
{{- $_ := set $local "first" false -}}
{{- end -}}
    },
    "params":{
      "FRONTEND_NAMESPACE": "{{ .Release.Namespace }}"
      "DELAY_SAVE_NOTIFICATION": "10000"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krateo-frontend.fullname" . }}
  labels:
    {{- include "krateo-frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}