apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krateo-frontend.fullname" . }}-config-vars
  labels:
    {{- include "krateo-frontend.labels" . | nindent 4 }}
data:
  config.json: |
    {"api":{
{{- $local := dict "first" true -}}
{{- range $k, $v := .Values.env -}}
{{- if not $local.first -}},{{- end -}}
{{- if kindIs "string" $v }}
  {{ quote $k | indent 6 }}: {{ quote $v }}
{{- else }}
  {{ quote $k | indent 6 }}: {{ $v }}
{{- end }}
{{- $_ := set $local "first" false -}}
{{- end -}}
    }}
