apiVersion: v1
kind: Service
metadata:
  name: {{ include "krateo-frontend.fullname" . }}
  labels:
    {{- include "krateo-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "krateo-frontend.selectorLabels" . | nindent 4 }}
